
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button btnStartStop;

	private global::Gtk.Label lblStatusValue;

	private global::Gtk.Label lblCurrentAlertLabel;

	private global::Gtk.Label lblLog;

	private global::Gtk.Label lblOldAlertLabel;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView tvCurrentAlert;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView tvOldAllert;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Smetko FBExtractor");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnStartStop = new global::Gtk.Button();
		this.btnStartStop.WidthRequest = 90;
		this.btnStartStop.HeightRequest = 43;
		this.btnStartStop.CanFocus = true;
		this.btnStartStop.Name = "btnStartStop";
		this.btnStartStop.UseUnderline = true;
		this.btnStartStop.Label = global::Mono.Unix.Catalog.GetString("Старт");
		this.fixed1.Add(this.btnStartStop);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnStartStop]));
		w1.X = 9;
		w1.Y = 14;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblStatusValue = new global::Gtk.Label();
		this.lblStatusValue.Name = "lblStatusValue";
		this.lblStatusValue.LabelProp = global::Mono.Unix.Catalog.GetString("Спрян");
		this.fixed1.Add(this.lblStatusValue);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblStatusValue]));
		w2.X = 121;
		w2.Y = 26;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblCurrentAlertLabel = new global::Gtk.Label();
		this.lblCurrentAlertLabel.Name = "lblCurrentAlertLabel";
		this.lblCurrentAlertLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Текущо известие:");
		this.fixed1.Add(this.lblCurrentAlertLabel);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblCurrentAlertLabel]));
		w3.X = 9;
		w3.Y = 103;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblLog = new global::Gtk.Label();
		this.lblLog.WidthRequest = 450;
		this.lblLog.HeightRequest = 80;
		this.lblLog.Name = "lblLog";
		this.lblLog.LabelProp = global::Mono.Unix.Catalog.GetString("<Статус>");
		this.lblLog.Wrap = true;
		this.fixed1.Add(this.lblLog);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblLog]));
		w4.X = 414;
		w4.Y = 11;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblOldAlertLabel = new global::Gtk.Label();
		this.lblOldAlertLabel.Name = "lblOldAlertLabel";
		this.lblOldAlertLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Предходно известие:");
		this.fixed1.Add(this.lblOldAlertLabel);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblOldAlertLabel]));
		w5.X = 8;
		w5.Y = 231;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tvCurrentAlert = new global::Gtk.TextView();
		this.tvCurrentAlert.WidthRequest = 600;
		this.tvCurrentAlert.CanFocus = true;
		this.tvCurrentAlert.Name = "tvCurrentAlert";
		this.tvCurrentAlert.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow.Add(this.tvCurrentAlert);
		this.fixed1.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
		w7.X = 5;
		w7.Y = 131;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.tvOldAllert = new global::Gtk.TextView();
		this.tvOldAllert.WidthRequest = 600;
		this.tvOldAllert.CanFocus = true;
		this.tvOldAllert.Name = "tvOldAllert";
		this.tvOldAllert.Editable = false;
		this.tvOldAllert.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow1.Add(this.tvOldAllert);
		this.fixed1.Add(this.GtkScrolledWindow1);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow1]));
		w9.X = 10;
		w9.Y = 268;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 864;
		this.DefaultHeight = 351;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnStartStop.Clicked += new global::System.EventHandler(this.OnToggleClickEvent);
	}
}
